pipelines:
  default:
    - step:
        name: Build & Deploy
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y zip
          - npm ci
          - cd client && npm ci && npm run build && cd ..
          - zip -r application.zip . -x "client/node_modules/*" -x "node_modules/*" -x ".git/*"
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $APPLICATION_NAME
              S3_BUCKET: $S3_BUCKET
              COMMAND: "upload"
              ZIP_FILE: "application.zip"
              VERSION_LABEL: "letsmoveit-right-${BITBUCKET_BUILD_NUMBER}"
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $APPLICATION_NAME
              DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
              S3_BUCKET: $S3_BUCKET
              COMMAND: "deploy"
              WAIT: "true"
              VERSION_LABEL: "letsmoveit-right-${BITBUCKET_BUILD_NUMBER}"
              IGNORE_APPLICATION_STOP_FAILURES: "true"
              FILE_EXISTS_BEHAVIOR: "OVERWRITE"
